import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { CheckCircle2, FileText, ArrowRight, Clock, ShieldCheck, MessageCircle, CalendarClock } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";

export const Route=createFileRoute("/claim/success")({component:ClaimSuccess,head:()=>({meta:[{title:"Dossierbegeleiding aangevraagd — uithoorn.online"},{name:"description",content:"Je aanvraag voor dossierbegeleiding is opgeslagen. Bekijk de vervolgstappen."}]})});
type ClaimRow={id:string;name:string;address:string;postcode:string;years_selected:number[];package:string;paid:boolean;contact_method:"phone"|"whatsapp"|null;contact_phone:string|null;meeting_requested:boolean;meeting_availability:string|null;created_at:string};
const officialLinks=[{href:"https://meldingen-bezoekbas.nl/",label:"BAS — officiële meldroute"},{href:"https://www.schiphol.nl/nl/schiphol-als-buur/",label:"Schiphol — informatie voor de omgeving"}];
function ClaimSuccess(){
 const {user,loading:authLoading}=useAuth(); const {id}=Route.useSearch(); const navigate=useNavigate(); const [claim,setClaim]=useState<ClaimRow|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(authLoading)return;if(!user){navigate({to:"/auth",search:{next:"/claim"}});return;}(async()=>{let q=supabase.from("claims").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1);if(id)q=supabase.from("claims").select("*").eq("user_id",user.id).eq("id",id).limit(1);const {data}=await q;setClaim((data?.[0] as ClaimRow)??null);setLoading(false)})()},[user,authLoading,id,navigate]);
 return <AppShell><section className="bg-navy px-5 pb-8 pt-7 text-navy-foreground sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-red"><CheckCircle2 size={23}/></div><div><div className="text-[10px] font-semibold uppercase tracking-[0.16em] text-white/55">Dossierbegeleiding</div><h1 className="mt-1 text-3xl sm:text-4xl">Aanvraag opgeslagen</h1><p className="mt-1 text-sm text-white/65">Je contactvoorkeur staat veilig in je Uithoorn Online-dossier.</p></div></div>{claim&&<div className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex justify-between text-xs"><span className="text-white/50">Referentie</span><span className="font-mono">{claim.id.slice(0,8).toUpperCase()}</span></div></div>}</div></section>
 <section className="mx-auto -mt-5 max-w-3xl space-y-4 px-5 pb-12 sm:px-6"><div className="rounded-2xl border border-border bg-white p-5 shadow-[0_18px_50px_rgba(13,31,60,.10)] sm:p-6"><div className="flex gap-3 rounded-xl border border-navy/10 bg-cream p-4"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-navy/60"/><p className="text-xs leading-5 text-navy/70"><strong className="text-navy">Dit is geen officiële aanvraag.</strong> Uithoorn Online heeft je interne dossier opgeslagen. Daarmee is geen recht op compensatie vastgesteld en is geen aanvraag bij een bevoegde instantie ingediend.</p></div>{loading?<p className="mt-6 text-sm text-muted-foreground">Aanvraag laden…</p>:claim?<><h2 className="mt-6 text-xl text-navy">Wat gebeurt er nu?</h2><ol className="mt-4 space-y-4"><Step n={1} Icon={CheckCircle2} title="Aanvraag ontvangen" desc="Je gegevens en contactvoorkeur zijn opgeslagen."/><Step n={2} Icon={MessageCircle} title={claim.contact_method==="whatsapp"?"Contact via WhatsApp":"Telefonisch contact"} desc="We gebruiken het door jou opgegeven nummer om contact op te nemen over de service."/>{claim.meeting_requested&&<Step n={3} Icon={CalendarClock} title="Gesprek aangevraagd" desc={claim.meeting_availability?`Je voorkeur: ${claim.meeting_availability}. De afspraak is pas definitief na bevestiging.`:"Je hebt een gesprek aangevraagd. De afspraak is pas definitief na bevestiging."}/>}<Step n={claim.meeting_requested?4:3} Icon={Clock} title="Servicebevestiging" desc="De servicekosten zijn €9,99. Een betaalverzoek en de definitieve afspraak worden afzonderlijk bevestigd."/></ol></>:<p className="mt-6 text-sm text-muted-foreground">Geen dossiergegevens gevonden.</p>}</div><NextActions/></section></AppShell>;
}
function NextActions(){return <div className="rounded-2xl border border-border bg-cream p-5"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-navy/45">Officiële routes</div><h2 className="mt-1 text-xl text-navy">Vervolg bij de bevoegde partij</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Uithoorn Online helpt informatie te ordenen. Officiële instanties bepalen rechten, compensatie en formele uitkomsten.</p><div className="mt-4 grid gap-2">{officialLinks.map(l=><a key={l.href} href={l.href} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-border bg-white px-4 py-3"><span className="text-sm font-medium text-navy">{l.label}</span><ArrowRight size={16} className="text-navy/50"/></a>)}<Link to="/log" className="flex items-center justify-between rounded-xl border border-border bg-white px-4 py-3"><span className="text-sm font-medium text-navy">Nieuwe overlastmelding</span><ArrowRight size={16} className="text-navy/50"/></Link><Link to="/" className="flex items-center justify-between rounded-xl border border-border bg-white px-4 py-3"><span className="text-sm font-medium text-navy">Vraag aan de assistent</span><ArrowRight size={16} className="text-navy/50"/></Link></div></div>}
function Step({n,Icon,title,desc}:{n:number;Icon:typeof CheckCircle2;title:string;desc:string}){return <li className="flex gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-navy text-xs font-mono text-white">{n}</div><div><div className="flex items-center gap-2 text-sm font-medium text-navy"><Icon size={15}/>{title}</div><p className="mt-0.5 text-xs leading-5 text-muted-foreground">{desc}</p></div></li>}
