import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { z } from "zod";
import { AppShell } from "@/components/AppShell";
import { CheckCircle2, FileText, Mail, Scale, ArrowRight, Clock, ShieldCheck, type LucideIcon } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";

const searchSchema = z.object({ id: z.string().optional(), pkg: z.enum(["self", "managed", "legal"]).optional() });
export const Route=createFileRoute("/claim/success")({validateSearch: searchSchema, component:ClaimSuccess,head:()=>({meta:[{title:"Dossier opgeslagen — uithoorn.online"},{name:"description",content:"Je dossier is opgeslagen. Bekijk de vervolgstappen en officiële routes."}]})});
type ClaimRow={id:string;name:string;address:string;postcode:string;years_selected:number[];package:"self"|"managed"|"legal";paid:boolean;created_at:string};
const officialLinks=[{href:"https://meldingen-bezoekbas.nl/",label:"BAS — officiële meldroute"},{href:"https://www.schiphol.nl/nl/schiphol-als-buur/",label:"Schiphol — informatie voor de omgeving"}];
function ClaimSuccess(){
 const {user,loading:authLoading}=useAuth(); const {id,pkg}=Route.useSearch(); const navigate=useNavigate(); const [claim,setClaim]=useState<ClaimRow|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(authLoading)return;if(!user){navigate({to:"/auth",search:{next:"/claim"}});return;}(async()=>{let q=supabase.from("claims").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1);if(id)q=supabase.from("claims").select("*").eq("user_id",user.id).eq("id",id).limit(1);const {data}=await q;setClaim((data?.[0] as ClaimRow)??null);setLoading(false)})()},[user,authLoading,id,navigate]);
 const activePkg=(claim?.package??pkg) as "self"|"managed"|"legal"|undefined;
 return <AppShell><section className="bg-navy px-5 pb-8 pt-7 text-navy-foreground sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl"><div className="flex items-center gap-3"><div className="grid h-11 w-11 items-center place-items-center rounded-full bg-red"><CheckCircle2 size={23}/></div><div><div className="text-[10px] font-semibold uppercase tracking-[0.16em] text-white/55">Dossier</div><h1 className="mt-1 text-3xl sm:text-4xl">Opgeslagen</h1><p className="mt-1 text-sm text-white/65">Je informatie staat veilig in je Uithoorn Online-dossier.</p></div></div>{claim&&<div className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex justify-between text-xs"><span className="text-white/50">Referentie</span><span className="font-mono">{claim.id.slice(0,8).toUpperCase()}</span></div><div className="mt-1 flex justify-between text-xs"><span className="text-white/50">Jaren</span><span>{claim.years_selected.join(", ")}</span></div></div>}</div></section>
 <section className="mx-auto -mt-5 max-w-3xl space-y-4 px-5 pb-12 sm:px-6"><div className="rounded-2xl border border-border bg-white p-5 shadow-[0_18px_50px_rgba(13,31,60,.10)] sm:p-6"><div className="flex gap-3 rounded-xl border border-navy/10 bg-cream p-4"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-navy/60"/><p className="text-xs leading-5 text-navy/70"><strong className="text-navy">Dit is geen officiële aanvraag.</strong> Uithoorn Online heeft een intern dossier opgeslagen. Daarmee is geen recht op compensatie vastgesteld en is geen aanvraag bij een bevoegde instantie ingediend.</p></div><h2 className="mt-6 text-xl text-navy">Wat gebeurt er nu?</h2>{loading?<p className="mt-3 text-sm text-muted-foreground">Dossier laden…</p>:activePkg==="self"?<SelfSteps/>:activePkg==="managed"?<ManagedSteps/>:activePkg==="legal"?<LegalSteps/>:<p className="mt-3 text-sm text-muted-foreground">Geen dossiergegevens gevonden.</p>}</div><NextActions/></section></AppShell>;
}
function NextActions(){return <div className="rounded-2xl border border-border bg-cream p-5"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-navy/45">Officiële routes</div><h2 className="mt-1 text-xl text-navy">Vervolg zelf bij de bevoegde partij</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Uithoorn Online helpt informatie te ordenen. Officiële instanties bepalen rechten, compensatie en formele uitkomsten.</p><div className="mt-4 grid gap-2">{officialLinks.map(l=><a key={l.href} href={l.href} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-border bg-white px-4 py-3"><span className="text-sm font-medium text-navy">{l.label}</span><ArrowRight size={16} className="text-navy/50"/></a>)}<Link to="/log" className="flex items-center justify-between rounded-xl border border-border bg-white px-4 py-3"><span className="text-sm font-medium text-navy">Nieuwe overlastmelding</span><ArrowRight size={16} className="text-navy/50"/></Link><Link to="/" className="flex items-center justify-between rounded-xl border border-border bg-white px-4 py-3"><span className="text-sm font-medium text-navy">Vraag aan de assistent</span><ArrowRight size={16} className="text-navy/50"/></Link></div></div>}
function Step({n,Icon,title,desc}:{n:number;Icon:LucideIcon;title:string;desc:string}){return <li className="flex gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-navy text-xs font-mono text-white">{n}</div><div><div className="flex items-center gap-2 text-sm font-medium text-navy"><Icon size={15}/>{title}</div><p className="mt-0.5 text-xs leading-5 text-muted-foreground">{desc}</p></div></li>}
function SelfSteps(){return <ol className="mt-4 space-y-4"><Step n={1} Icon={CheckCircle2} title="Dossier opgeslagen" desc="Je gegevens en gekozen jaren zijn vastgelegd."/><Step n={2} Icon={FileText} title="Officiële route controleren" desc="Gebruik de bevoegde instantie voor een officiële melding of aanvraag."/><Step n={3} Icon={Clock} title="Bewijs blijven verzamelen" desc="Log relevante overlastmomenten en bewaar documenten."/></ol>}
function ManagedSteps(){return <ol className="mt-4 space-y-4"><Step n={1} Icon={Clock} title="Dossier opgeslagen" desc="Je aanvraag voor dossierbegeleiding is vastgelegd."/><Step n={2} Icon={FileText} title="Dossier voorbereiden" desc="Aanvullende meldingen en documenten kunnen worden toegevoegd."/><Step n={3} Icon={Mail} title="Officiële vervolgstap" desc="Een officiële aanvraag bestaat pas wanneer die daadwerkelijk bij de bevoegde instantie is ingediend."/></ol>}
function LegalSteps(){return <ol className="mt-4 space-y-4"><Step n={1} Icon={Scale} title="Dossier opgeslagen" desc="Je aanvraag voor de gekozen service is vastgelegd."/><Step n={2} Icon={FileText} title="Dossier aanvullen" desc="Voeg relevante meldingen en documenten toe."/><Step n={3} Icon={Scale} title="Bevoegde beoordeling" desc="Een formele beslissing komt uitsluitend van de daarvoor bevoegde partij."/></ol>}
