import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Check, ChevronRight, FileText, Scale, Sparkles, CheckCircle2, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { toast } from "sonner";

type PackageChoice="self"|"managed"|"legal";
const PACKAGE_META:Record<PackageChoice,{title:string;price:string;desc:string}>={
 self:{title:"Zelf doen",price:"Gratis",desc:"Je dossieroverzicht en verwijzingen naar officiële routes."},
 managed:{title:"Dossierbegeleiding",price:"€100",desc:"Voorbereiding en ordening van je beschikbare informatie en bewijsstukken."},
 legal:{title:"Uitgebreide dossierbegeleiding",price:"€450",desc:"Uitgebreide intake en voorbereiding van vervolgstappen. Geen garantie op een juridische of officiële uitkomst."},
};
const CURRENT_YEAR=new Date().getFullYear(); const YEAR_OPTIONS=[CURRENT_YEAR-2,CURRENT_YEAR-1,CURRENT_YEAR]; const POSTCODE_RE=/^\d{4}\s?[A-Z]{2}$/; const STEP_LABELS=["Gegevens","Service","Bevestiging"] as const;
export const Route=createFileRoute("/claim/")({component:Claim,head:()=>({meta:[{title:"Dossier voorbereiden — uithoorn.online"},{name:"description",content:"Stel je eigen dossier samen met informatie en bewijs rond Schiphol-geluidsoverlast."}]})});
function Claim(){
 const {user,loading:authLoading}=useAuth(); const navigate=useNavigate(); const [step,setStep]=useState<1|2|3>(1); const [name,setName]=useState(""); const [address,setAddress]=useState(""); const [postcode,setPostcode]=useState(""); const [years,setYears]=useState<number[]>(YEAR_OPTIONS); const [pkg,setPkg]=useState<PackageChoice|null>(null); const [submitting,setSubmitting]=useState(false); const [dossierId,setDossierId]=useState<string|null>(null); const [agreed,setAgreed]=useState(false);
 const postcodeValid=POSTCODE_RE.test(postcode.trim()); const detailsValid=name.trim().length>1&&address.trim().length>3&&postcodeValid&&years.length>0; const toggleYear=(year:number)=>setYears(c=>c.includes(year)?c.filter(x=>x!==year):[...c,year].sort());
 const saveDossier=async()=>{if(!user){navigate({to:"/auth",search:{next:"/claim"}});return;}if(!pkg||!detailsValid||!agreed)return;setSubmitting(true);const {data,error}=await supabase.from("claims").insert({user_id:user.id,name:name.trim(),address:address.trim(),postcode:postcode.trim().toUpperCase(),years_selected:years,package:pkg,paid:pkg==="self"}).select("id").single();setSubmitting(false);if(error||!data){toast.error("Kon dossier niet opslaan");return;}setDossierId(data.id);setStep(3);toast.success("Dossier opgeslagen");};
 if(authLoading)return <AppShell><PageHero title="Dossier voorbereiden" eyebrow="Persoonlijk dossier" description="Je sessie wordt gecontroleerd…"/></AppShell>;
 if(!user)return <AppShell><PageHero title="Dossier voorbereiden" eyebrow="Persoonlijk dossier" description="Bewaar je verzamelde informatie veilig in je account."/><section className="mx-auto -mt-5 max-w-3xl px-5 pb-12 sm:px-6"><div className="rounded-2xl border border-border bg-white p-6 shadow-[0_18px_50px_rgba(13,31,60,.10)]"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-navy/60" size={19}/><p className="text-sm leading-6 text-navy/70">Uithoorn Online is geen overheidsinstantie en bepaalt niet of je recht hebt op compensatie.</p></div><Link to="/auth" search={{next:"/claim"}} className="mt-5 block rounded-xl bg-red py-3.5 text-center font-semibold text-white">Inloggen</Link></div></section></AppShell>;
 return <AppShell><PageHero title="Dossier voorbereiden" eyebrow="Persoonlijk dossier" description={<>Stap {step} van 3 · {STEP_LABELS[step-1]}</>} progress={step}/><section className="mx-auto -mt-5 max-w-3xl px-5 pb-12 sm:px-6"><div className="rounded-2xl border border-border bg-white shadow-[0_18px_50px_rgba(13,31,60,.10)]">
  <div className="p-5 sm:p-6">
   {step===1&&<div className="space-y-4"><SectionTitle title="Jouw gegevens" text="Deze gegevens worden gebruikt om je persoonlijke dossier samen te stellen."/><Field label="Volledige naam" value={name} onChange={setName} placeholder="Jan de Vries"/><Field label="Adres" value={address} onChange={setAddress} placeholder="Dorpsstraat 12"/><Field label="Postcode" value={postcode} onChange={v=>setPostcode(v.toUpperCase())} placeholder="1421 AB" maxLength={7}/>{postcode.length>0&&!postcodeValid&&<p className="text-[11px] text-red">Vul een geldige Nederlandse postcode in, bijvoorbeeld 1421 AB.</p>}<div><div className="text-xs font-semibold text-navy">Jaren met ervaren overlast</div><div className="mt-2 grid gap-2 sm:grid-cols-3">{YEAR_OPTIONS.map(year=>{const selected=years.includes(year);return <button type="button" key={year} onClick={()=>toggleYear(year)} className={`flex items-center gap-2 rounded-xl border px-4 py-3 text-left ${selected?"border-red bg-red/5":"border-border bg-cream"}`}><span className={`grid h-5 w-5 place-items-center rounded-md ${selected?"bg-red text-white":"border border-border bg-white"}`}>{selected&&<Check size={13}/>}</span><span className="font-serif text-navy">{year}</span></button>})}</div></div><button type="button" onClick={()=>setStep(2)} disabled={!detailsValid} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-red py-3.5 font-semibold text-white disabled:opacity-40">Naar servicekeuze <ChevronRight size={17}/></button></div>}
   {step===2&&<div className="space-y-4"><SectionTitle title="Kies een service" text="Kies hoe uitgebreid je ondersteuning bij het ordenen van je dossier moet zijn."/><div className="flex gap-3 rounded-xl border border-navy/10 bg-cream p-4"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-navy/60"/><p className="text-[11px] leading-5 text-navy/65"><strong className="text-navy">Belangrijk.</strong> Deze services bepalen geen recht op compensatie, geen bedrag en geen officiële uitkomst.</p></div>{(Object.keys(PACKAGE_META) as PackageChoice[]).map(choice=>{const meta=PACKAGE_META[choice];const Icon=choice==="self"?FileText:choice==="managed"?Sparkles:Scale;return <button type="button" key={choice} onClick={()=>setPkg(choice)} className={`w-full rounded-2xl border p-4 text-left transition ${pkg===choice?"border-red bg-red/5 shadow-sm":"border-border bg-white hover:border-navy/20"}`}><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-navy text-white"><Icon size={18}/></div><div className="min-w-0 flex-1"><div className="flex items-baseline justify-between gap-3"><h3 className="text-lg text-navy">{meta.title}</h3><span className="font-mono text-sm font-semibold text-navy">{meta.price}</span></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{meta.desc}</p></div><ChevronRight size={16} className="mt-3 shrink-0 text-navy/35"/></div></button>})}{pkg&&<label className="flex items-start gap-2 text-[11px] leading-5 text-muted-foreground"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)} className="mt-1 accent-red"/><span>Ik ga akkoord met de <Link to="/voorwaarden" className="text-navy underline">algemene voorwaarden</Link> en <Link to="/privacy" className="text-navy underline">privacyverklaring</Link>. Ik begrijp dat Uithoorn Online geen officiële beslissing of compensatie kan garanderen.</span></label>}<div className="flex gap-2"><button type="button" onClick={()=>setStep(1)} className="flex-1 rounded-xl border border-border py-3 text-sm font-medium text-navy">Terug</button><button type="button" onClick={saveDossier} disabled={!pkg||!agreed||submitting} className="flex-1 rounded-xl bg-red py-3 text-sm font-semibold text-white disabled:opacity-40">{submitting?"Opslaan…":"Dossier opslaan"}</button></div></div>}
   {step===3&&<div className="space-y-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-red"><CheckCircle2 size={23} className="text-white"/></div><div><h2 className="text-xl text-navy">Dossier opgeslagen</h2><p className="text-[11px] text-muted-foreground">Referentie {dossierId?dossierId.slice(0,8).toUpperCase():"—"}</p></div></div><div className="rounded-2xl bg-cream p-4 text-sm"><Row label="Naam" value={name}/><Row label="Adres" value={`${address}, ${postcode}`}/><Row label="Jaren" value={years.join(", ")}/><Row label="Service" value={pkg?PACKAGE_META[pkg].title:"—"}/><Row label="Servicekosten" value={pkg?PACKAGE_META[pkg].price:"—"}/></div>{pkg&&pkg!=="self"&&<div className="rounded-xl border border-amber-400/50 bg-amber-50 p-3 text-xs leading-5 text-amber-900">Er is nog niets betaald. Dit dossier is niet ingediend bij een officiële instantie. Voor betaalde dossierbegeleiding volgt, indien van toepassing, een afzonderlijk betaalverzoek volgens de servicevoorwaarden.</div>}<div className="rounded-xl border border-navy/10 bg-white p-4 text-xs leading-5 text-muted-foreground"><strong className="text-navy">Wat dit betekent:</strong> je hebt een dossier bij Uithoorn Online opgeslagen. Alleen een bevoegde instantie kan bepalen of je recht hebt op compensatie en welke formele uitkomst volgt.</div><Link to="/claim/success" search={{id:dossierId??undefined,pkg:pkg??undefined}} className="block w-full rounded-xl bg-red py-3.5 text-center font-semibold text-white">Bekijk vervolgstappen</Link><Link to="/log" className="block w-full rounded-xl border border-border py-3 text-center text-sm font-medium text-navy">Overlast loggen</Link></div>}
  </div></div></section></AppShell>;
}
function PageHero({eyebrow,title,description,progress}:{eyebrow:string;title:string;description:React.ReactNode;progress?:number}){return <section className="bg-navy px-5 pb-8 pt-7 text-navy-foreground sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.16em] text-white/55"><span className="h-1.5 w-1.5 rounded-full bg-red"/>{eyebrow}</div><h1 className="mt-3 text-3xl sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">{description}</p>{progress&&<div className="mt-5 grid grid-cols-3 gap-2">{STEP_LABELS.map((label,i)=><div key={label}><div className={`h-1.5 rounded-full ${progress>=i+1?"bg-red":"bg-white/15"}`}/><div className={`mt-1 text-[9px] uppercase tracking-wider ${progress>=i+1?"text-red":"text-white/35"}`}>{label}</div></div>)}</div>}</div></section>}
function SectionTitle({title,text}:{title:string;text:string}){return <div className="mb-2"><h2 className="text-xl text-navy">{title}</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4 border-b border-border/70 py-2.5 last:border-0"><span className="text-muted-foreground">{label}</span><span className="text-right text-navy">{value}</span></div>}
function Field({label,value,onChange,placeholder,maxLength}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;maxLength?:number}){return <div><label className="text-xs font-semibold text-navy">{label}</label><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} maxLength={maxLength} className="mt-1.5 w-full rounded-xl border border-border bg-cream px-3 py-3 text-sm outline-none"/></div>}
