import { redirect } from 'next/navigation';
import { ArrowRight, Bell, MessageCircle } from 'lucide-react';
import { createClient } from '../../lib/supabase/server';

export default async function AccountPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/login?next=/account');
  const [{ data: profile }, { data: requests }, { data: conversations }, { data: notifications }] = await Promise.all([
    supabase.from('profiles').select('full_name,role').eq('id', user.id).single(),
    supabase.from('service_requests').select('id,category,description,postcode,preferred_timing,status,created_at').eq('customer_id', user.id).order('created_at', { ascending: false }).limit(20),
    supabase.from('conversations').select('id,status,updated_at,businesses(name),service_requests(category)').eq('customer_id', user.id).order('updated_at', { ascending: false }).limit(20),
    supabase.from('notifications').select('id,title,body,read_at,created_at').eq('user_id', user.id).order('created_at', { ascending: false }).limit(10),
  ]);
  return <main className="platform-shell"><header className="platform-header"><a className="uo-brand" href="/"><span className="uo-brand-mark">u</span><span>ithoorn<span>.online</span></span></a><nav><a href="/request">Nieuwe aanvraag</a><form action="/api/auth/signout" method="post"><button>Uitloggen</button></form></nav></header><div className="platform-dashboard"><div className="platform-dashboard-head"><div><span className="uo-kicker">Mijn account</span><h1>Welkom{profile?.full_name ? `, ${profile.full_name}` : ''}.</h1><p>Beheer je aanvragen en gesprekken met lokale aanbieders.</p></div><a className="primary platform-button-link" href="/request">Nieuwe aanvraag <ArrowRight /></a></div><section className="dashboard-grid"><div className="dashboard-main"><div className="dashboard-section"><div className="dashboard-section-head"><h2>Mijn aanvragen</h2><span>{requests?.length || 0}</span></div>{requests?.length ? requests.map(request => <article className="request-row" key={request.id}><div><span>{request.category}</span><h3>{request.description}</h3><p>{request.postcode} · {request.preferred_timing}</p></div><strong>{request.status.replace('_', ' ')}</strong></article>) : <div className="dashboard-empty">Nog geen aanvragen. <a href="/request">Start je eerste aanvraag <ArrowRight /></a></div>}</div><div className="dashboard-section"><div className="dashboard-section-head"><h2>Gesprekken</h2><span>{conversations?.length || 0}</span></div>{conversations?.length ? conversations.map((conversation: any) => <a className="conversation-row" href={`/messages/${conversation.id}`} key={conversation.id}><MessageCircle /><div><strong>{conversation.businesses?.name || 'Lokale aanbieder'}</strong><small>{conversation.service_requests?.category || 'Aanvraag'}</small></div><span>{conversation.status}</span><ArrowRight /></a>) : <div className="dashboard-empty">Nog geen gesprekken. Een aanbieder kan reageren op je aanvraag.</div>}</div></div><aside className="dashboard-side"><div className="dashboard-section"><div className="dashboard-section-head"><h2>Meldingen</h2><Bell /></div>{notifications?.length ? notifications.map(notification => <div className={`notification-row ${notification.read_at ? 'read' : ''}`} key={notification.id}><strong>{notification.title}</strong><p>{notification.body}</p><small>{new Date(notification.created_at).toLocaleString('nl-NL')}</small></div>) : <div className="dashboard-empty">Geen nieuwe meldingen.</div>}</div></aside></section></div></main>;
}
