import type { Metadata } from 'next';
import './globals.css';
import './uo.css';
import './speakin-theme.css';
import './uopages.css';
import './locale.css';
import './brand-proof-fixes.css';
import './provider-profile.css';
import './agentic-home.css';
import './eci-theme.css';
import './agent-chat.css';
import './home-chat-overrides.css';
import './discovery-pages.css';
import './directory-conversion.css';
import './featured-ad.css';
import './home-services.css';
import './directory-marketplace.css';
import './marketplace-trust.css';
import './service-landing.css';
import './easy-redesign.css';
import { LocaleProvider } from '../components/locale-provider';
export const metadata: Metadata = { title: 'Uithoorn.online — Vind lokaal wat je nodig hebt.', description: 'Vind lokale bedrijven en diensten in Uithoorn en De Kwakel. Zoek een dienst of vertel wat je nodig hebt.', metadataBase: new URL('https://uithoorn.online'), icons: { icon: '/icon.svg', shortcut: '/icon.svg' } };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="nl"><body><LocaleProvider>{children}</LocaleProvider></body></html>; }
