import { cookies } from 'next/headers';
import { NextResponse } from 'next/server';
import { loadAgentState, saveAgentState } from '../../../lib/agent/session';
import { upsertAgentLead } from '../../../lib/supabase/leads';
import { applyOrchestratorDecision, applySpecialistResult, DEFAULT_AGENT_STATE, type AgentContact, type AgentState, type SemanticIntent } from '../../../lib/agent/state';
import { emergencyFromMessage } from '../../../lib/agent/planner';
import { runAgent, type UnifiedAgentResult } from '../../../lib/agent/agent-runtime';
import { runHarness } from '../../../lib/agent/harness/harness';
import { discoverGooglePlaces } from '../../../lib/agent/discovery';
import { searchVerifiedProviders, type AgentProvider } from '../../../lib/supabase/agent';
import type { ToolCapability, ToolExecutor } from '../../../lib/agent/harness/tool-gateway';

type ChatMessage={role:'user'|'assistant';content:string}; type ContactInput={name?:unknown;email?:unknown;phone?:unknown;address?:unknown};
const BUSINESS_INTENTS=new Set<SemanticIntent>(['find_food','order_food','find_service','find_business','find_event']);
const BACKEND_FAILURE_MESSAGE='Sorry, our technology is letting us down. Please call +31616270233 for immediate assistance.';
function backendFailureResponse(language:AgentState['language'],state:AgentState=DEFAULT_AGENT_STATE,safety=state.safety){return NextResponse.json({error:'backend_unavailable',reply:BACKEND_FAILURE_MESSAGE,actions:[],providers:[],render_mode:'message',state:{...state,language},safety},{status:503});}
function normalizeContact(value:unknown):AgentContact|null{if(!value||typeof value!=='object')return null;const i=value as ContactInput;const name=String(i.name??'').trim().replace(/\s+/g,' ');const email=String(i.email??'').trim().toLowerCase();const phone=String(i.phone??'').trim();const address=String(i.address??'').trim().replace(/\s+/g,' ');if(name.length<2||!/^([^\s@]+)@([^\s@]+)\.([^\s@]+)$/.test(email)||phone.replace(/\D/g,'').length<8||address.length<5||!/\d/.test(address))return null;return{name,email,phone,address};}
function normalizeHistory(value:unknown,currentMessage:string):ChatMessage[]{if(!Array.isArray(value))return[];const n:ChatMessage[]=value.filter((x):x is {role?:unknown;content?:unknown;text?:unknown}=>Boolean(x&&typeof x==='object')).map(x=>({role:(x.role==='assistant'?'assistant':'user') as ChatMessage['role'],content:String(x.content??x.text??'').trim()})).filter(x=>x.content.length>0);if(n.at(-1)?.role==='user'&&n.at(-1)?.content===currentMessage)n.pop();return n.slice(-8);}
function detectLanguage(text:string):'nl'|'en'{const w=new Set(text.toLowerCase().match(/[a-zà-ÿ]+/g)||[]);const nl=['ik','zoek','eten','catering','restaurant','bedrijf','loodgieter','elektricien','schoonmaak','vandaag','weekend','wat','nodig','hulp','graag'].reduce((n,x)=>n+(w.has(x)?1:0),0);const en=['i','need','food','catering','restaurant','business','plumber','electrician','cleaning','today','weekend','what','looking','help','please'].reduce((n,x)=>n+(w.has(x)?1:0),0);return en>nl?'en':'nl';}
function detectEmergencyLanguage(text:string):'nl'|'en'{const w=new Set(text.toLowerCase().match(/[a-zà-ÿ]+/g)||[]);const nl=['ik','hulp','112','brand','ambulance','politie','gevaar','nood','spoed','ongeluk','bloed'].reduce((n,x)=>n+(w.has(x)?1:0),0);const en=['i','help','112','fire','ambulance','police','danger','emergency','urgent','accident','blood'].reduce((n,x)=>n+(w.has(x)?1:0),0);return en>nl?'en':'nl';}
function applyAgentResult(agent:UnifiedAgentResult,previousState:AgentState,safety:AgentState['safety']){let state=applyOrchestratorDecision(agent.decision,previousState);state.safety=safety;state=applySpecialistResult(state,agent.specialist);return{state,specialist:agent.specialist};}

const executeAgentTool:ToolExecutor=async(state,query,capability:ToolCapability):Promise<AgentProvider[]>=>{
  if(capability==='business.search')return searchVerifiedProviders(query,state.location.postcode||'',5);
  if(capability==='business.discover')return discoverGooglePlaces(query,state.location.municipality,5);
  throw new Error(`unsupported_tool_capability:${capability}`);
};

export async function POST(request:Request){let requestMessage='';try{const body=await request.json();requestMessage=String(body.message||'').trim();const contactDecision=body.contact_decision==='no'?'no':body.contact_decision==='yes'?'yes':null;if(!requestMessage||requestMessage.length>4000)return NextResponse.json({error:'invalid_message'},{status:400});const safety=emergencyFromMessage(requestMessage);if(safety.emergency){const language=detectEmergencyLanguage(requestMessage);const reply=language==='en'?'This sounds like an emergency. **Call 112 now** for police, fire or ambulance.':'Dit klinkt als een noodsituatie. **Bel direct 112** voor politie, brandweer of ambulance.';return NextResponse.json({reply,state:{...DEFAULT_AGENT_STATE,language,languageLocked:true,safety},safety,actions:[{label:language==='en'?'Call 112':'Bel 112',value:'112',kind:'emergency'}],providers:[],render_mode:'message'});}const suppliedContact=normalizeContact(body.contact);const history=normalizeHistory(body.messages,requestMessage);const cookieStore=await cookies();let sessionKey=cookieStore.get('uo_agent_session')?.value;if(!sessionKey){sessionKey=crypto.randomUUID();cookieStore.set('uo_agent_session',sessionKey,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:60*60*24*30});}let previousState=DEFAULT_AGENT_STATE;try{previousState=(await loadAgentState(sessionKey))||DEFAULT_AGENT_STATE;}catch(error){console.error('AGENT_SESSION_LOAD_ERROR',error instanceof Error?error.message:'unknown_error');return backendFailureResponse(detectLanguage(requestMessage),DEFAULT_AGENT_STATE,safety);}if(previousState.contact&&previousState.contactCapture?.status!=='accepted')previousState={...previousState,contactCapture:{...previousState.contactCapture,status:'accepted'}};

let harnessResult:Awaited<ReturnType<typeof runHarness>>;try{harnessResult=await runHarness(requestMessage,history,previousState,runAgent,executeAgentTool);}catch(error){console.error('AGENT_HARNESS_ERROR',error instanceof Error?error.message:'unknown_error');return backendFailureResponse(previousState.language,previousState,safety);}
const applied=applyAgentResult(harnessResult.agent,previousState,safety);let state={...harnessResult.state,...applied.state,harness:harnessResult.state.harness};const specialistResult=applied.specialist;
if(contactDecision==='no')state.contactCapture={status:'declined',promptIntent:previousState.contactCapture?.promptIntent||state.intent.primary,pendingMessage:null};
if(suppliedContact){state.contact=suppliedContact;state.contactCapture={status:'accepted',promptIntent:previousState.contactCapture?.promptIntent||state.intent.primary,pendingMessage:null};try{await upsertAgentLead(sessionKey,suppliedContact,state.language,state.contactCapture.promptIntent||state.intent.primary);}catch(error){console.error('AGENT_LEAD_SAVE_ERROR',error instanceof Error?error.message:'unknown_error');return backendFailureResponse(state.language,state,safety);}}

const providers=harnessResult.providers;state.task={...state.task,status:providers.length>0?'completed':state.task.status};if(providers.length===1)state.activeProviderId=providers[0].id;try{await saveAgentState(sessionKey,state);}catch(error){console.error('AGENT_SESSION_SAVE_ERROR',error instanceof Error?error.message:'unknown_error');return backendFailureResponse(state.language,state,safety);}
const hasProviderResults=providers.length>0;const reply=hasProviderResults?'':specialistResult.reply;const contactOffer=BUSINESS_INTENTS.has(state.intent.primary)&&!state.contact&&state.contactCapture.status==='unknown';if(contactOffer)state.contactCapture={status:'offered',promptIntent:state.intent.primary,pendingMessage:requestMessage};return NextResponse.json({reply,render_mode:hasProviderResults?'provider_cards':'message',state,safety:state.safety,contact_offer:contactOffer,actions:contactOffer?(state.language==='en'?[{label:'Yes',value:'__contact_yes',kind:'contact_yes'},{label:'No',value:'__contact_no',kind:'contact_no'}]:[{label:'Ja',value:'__contact_yes',kind:'contact_yes'},{label:'Nee',value:'__contact_no',kind:'contact_no'}]):[],providers:providers.map(({id,name,category,description,postcode,phone,website,verified,rating_score,rating_max,rating_review_count,rating_source,rating_source,rating_review_count,source_url,agent_metadata})=>({id,name,category,description,postcode,phone,website,verified,rating_score,rating_max,rating_review_count,rating_source,source_url,external_source:agent_metadata?.discovery_source||null}))});}catch(error){console.error('AGENT_ERROR',error instanceof Error?error.message:'unknown_error');return backendFailureResponse(detectLanguage(requestMessage),{...DEFAULT_AGENT_STATE,language:detectLanguage(requestMessage)},{emergency:false,reason:null});}}
