'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, MapPin, Menu, Search, Sparkles, Wrench, X } from 'lucide-react';
import { workshops } from '../data';

const nav = [['Diensten', 'services'], ['Activiteiten', 'workshops'], ['Eten & drinken', 'food']] as const;
const serviceHighlights = [
  { title: 'Klus & onderhoud', text: 'Vind lokale professionals voor onderhoud, reparatie en klussen.', mark: '01' },
  { title: 'Schoonmaak & hulp', text: 'Ontdek lokale hulp voor huis, ramen en specialistische reiniging.', mark: '02' },
  { title: 'Techniek & installatie', text: 'Vind lokale vakmensen voor installatie en technische hulp.', mark: '03' },
];

function scrollToSection(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }

export function HomePage() {
  const [query, setQuery] = useState('');
  const [mobileOpen, setMobileOpen] = useState(false);
  const q = query.trim().toLowerCase();
  const workshopResults = useMemo(() => workshops.filter((item) => `${item.title} ${item.provider} ${item.meta} ${item.description}`.toLowerCase().includes(q)), [q]);
  const foodMatch = q && ['indian', 'indiaas', 'food', 'eten', 'dosa', 'idli', 'vada', 'biryani', 'spiceindia'].some((term) => q.includes(term));
  const total = q ? workshopResults.length + (foodMatch ? 1 : 0) : 0;

  return (
    <main className="uo-site" id="top">
      <header className="uo-header"><div className="uo-header-inner"><a href="#top" className="uo-brand" aria-label="Uithoorn.online home"><span className="uo-brand-mark" aria-hidden="true"><img src="/icon.svg" alt="" /></span><span className="uo-brand-wordmark">uithoorn<span>.online</span></span><small className="uo-brand-tagline">Lokaal in Uithoorn</small></a><nav className="uo-nav" aria-label="Hoofdnavigatie"><button onClick={() => scrollToSection('explore')}>Ontdek</button>{nav.map(([label, id]) => <button key={id} onClick={() => scrollToSection(id)}>{label}</button>)}</nav><div className="uo-header-actions"><span className="uo-location"><MapPin /> Uithoorn & De Kwakel</span><a className="uo-header-cta" href="/signup">Voor ondernemers</a><button className="uo-menu" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Menu" aria-expanded={mobileOpen}>{mobileOpen ? <X /> : <Menu />}</button></div></div>{mobileOpen && <nav className="uo-mobile-nav" aria-label="Mobiele navigatie"><button onClick={() => { scrollToSection('explore'); setMobileOpen(false); }}>Ontdek</button>{nav.map(([label, id]) => <button key={id} onClick={() => { scrollToSection(id); setMobileOpen(false); }}>{label}</button>)}<a href="/businesses">Lokale aanbieders</a><a href="/signup">Voor ondernemers</a></nav>}</header>

      <section className="uo-hero" id="explore"><div className="uo-hero-copy"><div className="uo-eyebrow"><MapPin /> Uithoorn & De Kwakel</div><h1>Vind wat je<br /><em>lokaal nodig hebt.</em></h1><p>Ontdek betrouwbare lokale aanbieders, activiteiten en eten in Uithoorn en De Kwakel — en kom direct in actie.</p><div className="uo-hero-links"><a href="/services">Vind een dienst <ArrowRight /></a><a href="/workshops">Ontdek activiteiten <ArrowRight /></a></div></div><div className="uo-search-wrap"><div className="uo-search-label">ZOEK LOKAAL</div><div className="uo-search" role="search"><Search aria-hidden="true" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Wat heb je lokaal nodig? Bijvoorbeeld schilder, keramiek of eten" aria-label="Zoek lokaal in Uithoorn" />{q && <button onClick={() => setQuery('')} aria-label="Zoekopdracht wissen"><X /></button>}</div><div className="uo-search-hints"><span>Probeer</span><button onClick={() => setQuery('schilder')}>schilder</button><button onClick={() => setQuery('keramiek')}>keramiek</button><button onClick={() => setQuery('biryani')}>biryani</button></div><div className="uo-search-note"><span>Lokale ontdekking</span><strong>Uithoorn + De Kwakel</strong></div></div></section>

      <section className="uo-platform-strip" aria-label="Wat je lokaal kunt vinden"><div><span>01</span><strong>Vind</strong><small>Lokale diensten</small></div><div><span>02</span><strong>Doe</strong><small>Activiteiten & workshops</small></div><div><span>03</span><strong>Eet</strong><small>Food & drink</small></div><div><span>04</span><strong>Ontdek</strong><small>Lokale bedrijven & plekken</small></div></section>

      {q ? <section className="uo-results" aria-live="polite"><div className="uo-section-head"><div><span className="uo-kicker">Lokale zoekresultaten</span><h2>{total} resultaten voor <em>“{query}”</em></h2></div><button onClick={() => setQuery('')} className="uo-text-button">Wis zoekopdracht <ArrowRight /></button></div>{total === 0 ? <div className="uo-empty"><Search /><h3>Nog niets gevonden</h3><p>Probeer een andere zoekterm. Voor lokale diensten kun je ook direct de geverifieerde aanbieders bekijken.</p><a href="/businesses">Bekijk geverifieerde aanbieders <ArrowRight /></a></div> : <div className="uo-result-groups">{workshopResults.length > 0 && <div><div className="uo-result-label">Activiteiten & workshops <b>{workshopResults.length}</b></div><div className="uo-list">{workshopResults.map((item) => <article key={item.title}><div><span>{item.provider}</span><h3>{item.title}</h3><p>{item.description}</p></div><strong>{item.meta}</strong></article>)}</div></div>}{foodMatch && <div><div className="uo-result-label">Food & drink <b>1</b></div><article className="uo-food-feature uo-spice"><div><span>SPICEINDIA</span><h3>South Indian food in Uithoorn</h3><p>Andhra-style biryani · dosa · idli · vada</p></div><a href="https://www.spiceindia.nl/">Bekijk menu <ArrowRight /></a></article></div>}</div>}</section> : <>
        <section className="uo-section uo-intro-section"><div className="uo-section-head"><div><span className="uo-kicker">LOKALE HULP, ACTIVITEITEN & ONTDEKKING</span><h2>Zoeken is het begin.<br /><em>Vinden is het doel.</em></h2></div><p className="uo-section-lead">Uithoorn.online helpt inwoners van Uithoorn en De Kwakel van een lokale zoekvraag naar een bruikbare volgende stap.</p></div><div className="uo-service-grid">{serviceHighlights.map((item) => <article key={item.mark}><span className="uo-number">{item.mark}</span><Wrench /><h3>{item.title}</h3><p>{item.text}</p><a href="/businesses">Bekijk lokale aanbieders <ArrowRight /></a></article>)}</div></section>
        <section className="uo-proof-section" aria-labelledby="local-proof-title"><div className="uo-proof-inner"><div><span className="uo-kicker">DE LOKALE ROUTE</span><h2 id="local-proof-title">Van lokale vraag<br /><em>naar actie.</em></h2></div><div className="uo-proof-copy"><p>Zoek wat je nodig hebt, ontdek relevante lokale opties en ga direct door naar de volgende stap — contact, website, aanvraag, boeking of bestelling.</p><a href="/businesses">Ontdek lokale aanbieders <ArrowRight /></a></div></div><div className="uo-proof-pillars"><article><strong>01</strong><h3>Zoek</h3><p>Beschrijf wat je lokaal nodig hebt.</p></article><article><strong>02</strong><h3>Ontdek</h3><p>Vind relevante lokale aanbieders en activiteiten.</p></article><article><strong>03</strong><h3>Vertrouw</h3><p>Bekijk duidelijke, geverifieerde informatie waar beschikbaar.</p></article><article><strong>04</strong><h3>Kom in actie</h3><p>Bel, bezoek, boek, bestel of vraag direct contact.</p></article></div></section>
        <section className="uo-section" id="workshops"><div className="uo-section-head"><div><span className="uo-kicker">02 · ACTIVITEITEN</span><h2>Doe iets lokaal.<br /><em>Ontdek iets nieuws.</em></h2></div><a href="/workshops">Alle activiteiten <ArrowRight /></a></div><div className="uo-workshop-grid">{workshops.slice(0, 3).map((item, index) => <article key={item.title}><div className={`uo-workshop-art art-${index + 1}`}><span>{String(index + 1).padStart(2, '0')}</span><Sparkles /></div><div className="uo-card-body"><span>{item.provider}</span><h3>{item.title}</h3><p>{item.description}</p><small><MapPin /> {item.meta}</small><a href="/workshops">Bekijk activiteit <ArrowRight /></a></div></article>)}</div></section>
        <section className="uo-feature-section"><div className="uo-feature-copy"><span className="uo-kicker">03 · FOOD & DRINK</span><h2>Ontdek lokaal eten.<br /><em>Direct naar de bron.</em></h2><p>Vind lokale food businesses en ga direct door naar menu, website of contact.</p><a href="/food">Ontdek food & drink <ArrowRight /></a></div><div className="uo-feature-visual"><span>FOOD & DRINK</span><strong>Local food<br />in Uithoorn</strong><small>Uithoorn · De Kwakel</small></div></section>
        <section className="uo-section uo-providers" id="providers"><div className="uo-section-head"><div><span className="uo-kicker">VOORZIENING & DIENSTEN</span><h2>Vind lokale aanbieders die je kunt benaderen.</h2></div><a href="/businesses">Alle aanbieders <ArrowRight /></a></div><div className="uo-provider-list uo-provider-list-empty"><div><strong>Geverifieerde lokale aanbieders</strong><small>De openbare gids toont alleen actieve aanbieders die door Uithoorn.online zijn geverifieerd.</small></div><a href="/businesses">Bekijk gids <ArrowRight /></a></div></section>
        <section className="uo-editorial"><div className="uo-editorial-head"><span className="uo-kicker">WAAROM UITHOORN.ONLINE</span><h2>Gebouwd rond lokale intentie.</h2></div><div className="uo-editorial-grid"><article><span>01</span><h3>Lokaal relevant</h3><p>Zoekopdrachten zijn gericht op Uithoorn en De Kwakel, niet op eindeloze landelijke resultaten.</p></article><article><span>02</span><h3>Van zoeken naar actie</h3><p>Het doel is niet alleen informatie tonen, maar je snel naar contact, boeking, bestelling of bezoek brengen.</p></article><article><span>03</span><h3>Vertrouwen voorop</h3><p>Providerinformatie wordt duidelijk onderscheiden van redactionele of voorbeeldcontent.</p></article></div></section>
      </>}
      <section className="uo-business-cta"><div><span className="uo-kicker">VOOR LOKALE ONDERNEMERS</span><h2>Word gevonden<br /><em>wanneer mensen zoeken.</em></h2><p>Maak je bedrijf zichtbaar voor inwoners van Uithoorn en De Kwakel met een duidelijk lokaal profiel.</p></div><a href="/signup">Word zichtbaar <ArrowRight /></a></section>
      <footer className="uo-footer"><a href="#top" className="uo-brand"><span className="uo-brand-mark" aria-hidden="true"><img src="/icon.svg" alt="" /></span><span className="uo-brand-wordmark">uithoorn<span>.online</span></span></a><span>Uithoorn & De Kwakel</span><span>© 2026 Uithoorn.online</span></footer>
    </main>
  );
}
