'use client';

import { FormEvent, useState } from 'react';
import { ArrowRight, Check } from 'lucide-react';
import { createClient } from '../lib/supabase/client';

type Business = { id: string; name: string; category: string; description: string; postcode: string | null; address: string | null; website: string | null; phone: string | null; verified: boolean };
const categories = ['Klus & onderhoud','Schoonmaak','Elektricien & installatie','Tuin & buiten','Loodgieter','Transport & logistiek','Automotive','Kapper & beauty','Eten & catering','Professionele diensten'];
export default function ProviderProfileForm({ business }: { business: Business }) {
  const [form, setForm] = useState({ name: business.name, category: business.category, description: business.description, postcode: business.postcode || '', address: business.address || '', website: business.website || '', phone: business.phone || '' });
  const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState('');
  const update = (key: keyof typeof form, value: string) => { setSaved(false); setForm((current) => ({ ...current, [key]: value })); };
  async function submit(event: FormEvent) { event.preventDefault(); if (saving) return; setSaving(true); setError(''); setSaved(false); try { const supabase = createClient(); const { error } = await supabase.from('businesses').update({ name: form.name.trim(), category: form.category, description: form.description.trim(), postcode: form.postcode.trim().toUpperCase(), address: form.address.trim(), website: form.website.trim(), phone: form.phone.trim() }).eq('id', business.id); if (error) throw error; setSaved(true); } catch { setError('Je profiel kon niet worden opgeslagen. Controleer je gegevens en probeer opnieuw.'); } finally { setSaving(false); } }
  return <form className="platform-form provider-profile-edit" onSubmit={submit}><label>Bedrijfsnaam<input required value={form.name} onChange={(e) => update('name', e.target.value)} /></label><label>Categorie<select value={form.category} onChange={(e) => update('category', e.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Beschrijving<textarea required minLength={20} value={form.description} onChange={(e) => update('description', e.target.value)} /></label><label>Postcode<input required value={form.postcode} onChange={(e) => update('postcode', e.target.value.toUpperCase())} /></label><label>Adres<input value={form.address} onChange={(e) => update('address', e.target.value)} /></label><label>Website<input type="url" placeholder="https://" value={form.website} onChange={(e) => update('website', e.target.value)} /></label><label>Telefoon<input type="tel" value={form.phone} onChange={(e) => update('phone', e.target.value)} /></label>{business.verified && <p className="verification-note"><Check /> Geverifieerd profiel. Wijzigingen worden opnieuw gecontroleerd wanneer nodig.</p>}{error && <p className="platform-error" role="alert">{error}</p>}{saved && <p className="review-success" role="status"><Check /> Profiel opgeslagen.</p>}<button className="primary" disabled={saving} type="submit">{saving ? 'Opslaan…' : 'Profiel opslaan'} <ArrowRight /></button></form>;
}
