import type { Metadata } from 'next';
import { ArrowRight, BarChart3, Check, MessageCircle, MessageSquareText, Search, ShieldCheck, Target, Users } from 'lucide-react';
import { WhatsAppPlanButton } from '../../components/whatsapp-plan-button';

export const metadata: Metadata = { title: 'Voor bedrijven — Groei met Uithoorn.online', description: 'Krijg lokale klantaanvragen, meet je bereik en groei met Uithoorn.online.' };

const plans = [
  { key: 'free' as const, name: 'Gratis', price: '€0', description: 'Een professionele basisvermelding voor lokale bedrijven.', features: ['Bedrijfsprofiel', 'Diensten en contactgegevens', 'Basis klantaanvragen', '3 leads per maand'], cta: 'Gratis starten' },
  { key: 'pro' as const, name: 'Pro', price: '29', description: 'Voor bedrijven die structureel lokale aanvragen willen ontvangen.', features: ['Alles van Gratis', '15 leads per maand', 'Lead- en contactinzichten', 'WhatsApp en extra contactacties', 'Geverifieerd bedrijfsprofiel'], cta: 'Start Pro' },
  { key: 'pro_plus' as const, name: 'Pro+', price: '59', description: 'Voor bedrijven die maximale lokale zichtbaarheid en groei willen.', features: ['Alles van Pro', '50 leads per maand', 'Featured en Local Spotlight', 'Geavanceerde analytics', 'AI-profieloptimalisatie'], cta: 'Start Pro+' },
];

export default function ForBusinessesPage() {
  return <main className="business-page"><header className="business-page-header"><a href="/" className="business-brand"><span className="business-brand-mark"><img src="/icon.svg" alt="" /></span><strong>Uithoorn<span>.online</span></strong></a><nav><a href="/businesses">Diensten</a><a href="/request">Hulp aanvragen</a><a className="active" href="/voor-bedrijven">Voor bedrijven</a></nav><a className="business-login" href="/provider">Bedrijfsdashboard <ArrowRight /></a></header>
    <section className="business-hero"><div className="business-hero-copy"><span className="business-kicker">VOOR BEDRIJVEN</span><h1>Word zichtbaar op het moment dat iemand hulp nodig heeft.</h1><p>Uithoorn.online verbindt lokale bewoners met bedrijven. Je profiel is gratis. Betaalde plannen geven je meer leads, inzicht en promotie.</p><div className="business-hero-actions"><a className="business-main-cta" href="/signup/account?role=provider">Claim je bedrijf <ArrowRight /></a><a className="business-secondary-cta" href="#prijzen">Bekijk prijzen</a></div></div><div className="business-hero-proof"><div><strong>Lokale vraag</strong><span>Bewoner zoekt een dienst</span></div><ArrowRight /><div><strong>Match</strong><span>Uithoorn.online vindt passende bedrijven</span></div><ArrowRight /><div><strong>Lead</strong><span>Je ontvangt een echte aanvraag</span></div></div></section>
    <section className="business-benefits"><div className="business-section-intro"><span className="business-kicker">ÉÉN PLATFORM</span><h2>Van lokale zoekopdracht naar klant.</h2></div><div className="business-benefit-grid"><article><Search /><h3>Word gevonden</h3><p>Een helder lokaal profiel met diensten, contactgegevens en verificatie.</p></article><article><Target /><h3>Ontvang passende aanvragen</h3><p>We koppelen klantvragen aan bedrijven die bij de behoefte passen.</p></article><article><BarChart3 /><h3>Meet je resultaat</h3><p>Zie profielweergaven, contactacties en leads in je bedrijfsdashboard.</p></article><article><ShieldCheck /><h3>Bouw vertrouwen</h3><p>Verificatie, gesprekken en reviews maken lokale keuze eenvoudiger.</p></article></div></section>
    <section className="business-pricing" id="prijzen"><div className="business-section-intro centered"><span className="business-kicker">PRIJZEN</span><h2>Kies hoe je wilt groeien.</h2><p>Begin gratis. Upgrade wanneer Uithoorn.online aantoonbaar waarde voor je bedrijf levert. Betaling en activatie regelen we persoonlijk via WhatsApp.</p></div><div className="pricing-grid">{plans.map(plan => <article key={plan.key} className={`pricing-card ${plan.key === 'pro_plus' ? 'featured' : ''}`}>{plan.key === 'pro_plus' ? <span className="pricing-badge">MEEST GEKOZEN</span> : null}<div className="pricing-head"><h3>{plan.name}</h3><p>{plan.description}</p></div><div className="pricing-price"><strong>{plan.price}</strong>{plan.key !== 'free' ? <span>/ maand</span> : null}</div><ul>{plan.features.map(feature => <li key={feature}><Check />{feature}</li>)}</ul>{plan.key === 'free' ? <a className="pricing-button" href="/signup/account?role=provider">{plan.cta}<ArrowRight /></a> : <WhatsAppPlanButton plan={plan.name as 'Pro' | 'Pro+'} price={plan.price} />}</article>)}</div><div className="whatsapp-payment-note" id="whatsapp"><MessageCircle /><div><strong>Betaling via WhatsApp</strong><span>Kies Pro of Pro+, stuur ons via WhatsApp je bedrijfsgegevens en wij sturen de betaalgegevens en activeringsinformatie.</span></div></div></section>
    <section className="business-lead-engine"><div><span className="business-kicker">DE LEADMOTOR</span><h2>Je betaalt voor bedrijfswaarde, niet voor ruis.</h2><p>Gekwalificeerde klantvragen bevatten een duidelijke behoefte, locatie en context. Lead- en promotiebetalingen kunnen rechtstreeks via WhatsApp worden afgehandeld.</p></div><div className="business-lead-flow"><div><Users /><strong>Bewoner</strong><span>Heeft een concrete behoefte</span></div><ArrowRight /><div><MessageSquareText /><strong>Uithoorn.online</strong><span>Matcht en levert de aanvraag</span></div><ArrowRight /><div><Target /><strong>Bedrijf</strong><span>Reageert en wint de klant</span></div></div></section>
    <section className="business-final-cta"><span className="business-kicker">KLAAR OM TE GROEIEN?</span><h2>Claim je lokale profiel.</h2><p>Start gratis en bouw vanuit echte lokale klantvragen.</p><a className="business-main-cta" href="/signup/account?role=provider">Voor bedrijven <ArrowRight /></a></section>
    <footer className="business-page-footer"><strong>Uithoorn<span>.online</span></strong><div><a href="/businesses">Diensten</a><a href="/request">Hulp aanvragen</a><a href="/">Home</a></div><small>Uithoorn &amp; De Kwakel · © 2026</small></footer>
  </main>;
}
