import type { Metadata } from 'next';
import { ArrowRight, BadgeCheck, MapPin } from 'lucide-react';
import { notFound } from 'next/navigation';
import { createClient } from '../../../lib/supabase/server';

const services: Record<string, { title: string; category: string; terms: string[] }> = {
  'loodgieter-uithoorn': { title: 'Loodgieter in Uithoorn', category: 'Loodgieter', terms: ['loodgiet','plumb','lekkage','water','verwarming','cv'] },
  'elektricien-uithoorn': { title: 'Elektricien in Uithoorn', category: 'Elektricien', terms: ['elektr','electric','install'] },
  'tuinman-uithoorn': { title: 'Tuinman in Uithoorn', category: 'Tuin & groen', terms: ['tuin','garden','hovenier','landschap','bestrating'] },
  'schoonmaker-uithoorn': { title: 'Schoonmaker in Uithoorn', category: 'Schoonmaak', terms: ['schoon','clean','huishoud','ramen'] },
  'handyman-uithoorn': { title: 'Handyman in Uithoorn', category: 'Handyman', terms: ['handyman','klus','reparatie','onderhoud','montage'] },
  'verhuizer-uithoorn': { title: 'Verhuizer in Uithoorn', category: 'Transport & verhuizen', terms: ['verhuis','moving','transport','koerier'] },
};

export async function generateStaticParams() { return Object.keys(services).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const service = services[slug]; return service ? { title: `${service.title} — Uithoorn.online`, description: `Vind geverifieerde ${service.category.toLowerCase()} in Uithoorn en De Kwakel. Plaats een hulpvraag en laat Uithoorn.online passende lokale aanbieders vinden.` } : { title: 'Lokale dienst — Uithoorn.online' }; }

export default async function ServiceLandingPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const service = services[slug]; if (!service) notFound();
  const supabase = await createClient();
  const { data: businesses } = await supabase.from('businesses').select('id,name,category,description,postcode,verified').eq('active', true).eq('verified', true).or(service.terms.map((term) => `category.ilike.%${term}%,description.ilike.%${term}%`).join(',')).limit(20);
  return <main className="uo-site uo-directory"><header className="uo-header"><div className="uo-header-inner"><a href="/" className="uo-brand"><span className="uo-brand-mark"><img src="/icon.svg" alt="" /></span><span>ithoorn<span>.online</span></span></a><nav className="uo-nav"><a href="/businesses">Bedrijven</a><a href="/events">Agenda</a><a href="/deals">Aanbiedingen</a></nav><div className="uo-header-actions"><span className="uo-location"><MapPin /> Uithoorn & De Kwakel</span><a className="uo-header-cta" href="/signup/account?role=provider">Bedrijf toevoegen</a></div></div></header><section className="service-landing"><span className="uo-kicker">Lokale dienst</span><h1>{service.title}</h1><p>Vind een geverifieerde lokale aanbieder in Uithoorn en De Kwakel. Liever niet zelf zoeken? Beschrijf je klus en laat ons passende aanbieders vinden.</p><div className="service-landing-actions"><a className="primary" href={`/request?category=${encodeURIComponent(service.category)}`}>Plaats een hulpvraag <ArrowRight /></a><a className="secondary" href="/businesses">Alle aanbieders</a></div><div className="service-landing-results"><div className="provider-profile-section-head"><div><span className="uo-kicker">Beschikbaar op Uithoorn.online</span><h2>{businesses?.length || 0} geverifieerde aanbieders</h2></div></div>{businesses?.length ? <div className="directory-provider-cards">{businesses.map((business) => <article className="directory-provider-card" key={business.id}><div className="directory-provider-avatar">{business.name.slice(0,1)}</div><div className="directory-provider-copy"><div className="directory-provider-topline"><span>{business.category}</span>{business.verified && <span className="directory-provider-verified"><BadgeCheck /> Geverifieerd</span>}</div><h3>{business.name}</h3><p>{business.description || `Lokale ${service.category.toLowerCase()} in Uithoorn.`}</p><div className="directory-provider-meta"><span><MapPin /> Uithoorn · {business.postcode || 'lokaal'}</span></div><a href={`/businesses/${business.id}`}>Bekijk profiel <ArrowRight /></a></div></article>)}</div> : <div className="uo-empty"><MapPin /><h3>Nog geen geverifieerde aanbieder voor deze dienst</h3><p>Laat je aanvraag achter. We gebruiken je behoefte om de juiste lokale aanbieder te vinden.</p><a href={`/request?category=${encodeURIComponent(service.category)}`}>Start je hulpvraag <ArrowRight /></a></div>}</div></section><footer className="uo-footer"><a href="/" className="uo-brand"><span className="uo-brand-mark"><img src="/icon.svg" alt="" /></span><span>ithoorn<span>.online</span></span></a><span>Uithoorn & De Kwakel</span><span>© 2026 Uithoorn.online</span></footer></main>;
}
