import { redirect } from 'next/navigation';
import { ArrowRight, BriefcaseBusiness, MessageCircle } from 'lucide-react';
import { createClient } from '../../lib/supabase/server';
import { ProviderAcceptButton } from '../../components/provider-request-actions';

export default async function ProviderPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/login?next=/provider');
  const { data: business } = await supabase.from('businesses').select('id,name,category,description,postcode,verified,active').eq('owner_id', user.id).limit(1).maybeSingle();
  if (!business) redirect('/signup');
  const [{ data: matches }, { data: conversations }, { data: notifications }] = await Promise.all([
    supabase.from('request_providers').select('request_id,status,invited_at,service_requests(id,category,description,postcode,preferred_timing,status,created_at)').eq('business_id', business.id).order('invited_at', { ascending: false }).limit(30),
    supabase.from('conversations').select('id,status,updated_at,service_requests(category,description)').eq('business_id', business.id).order('updated_at', { ascending: false }).limit(20),
    supabase.from('notifications').select('id,title,body,read_at,created_at').eq('user_id', user.id).order('created_at', { ascending: false }).limit(10),
  ]);
  const pending = (matches || []).filter((item: any) => item.status === 'invited');
  return <main className="platform-shell"><header className="platform-header"><a className="uo-brand" href="/"><span className="uo-brand-mark">u</span><span>ithoorn<span>.online</span></span></a><nav><a href="/businesses">Gids</a><form action="/api/auth/signout" method="post"><button>Uitloggen</button></form></nav></header><div className="platform-dashboard"><div className="provider-profile-strip"><div className="provider-avatar"><BriefcaseBusiness /></div><div><span className="uo-kicker">Lokale aanbieder</span><h1>{business.name}</h1><p>{business.category} · {business.postcode || 'Uithoorn'}</p></div><span className={`verification-pill ${business.verified ? 'verified' : ''}`}>{business.verified ? 'Geverifieerd' : 'In beoordeling'}</span></div><div className="metric-strip"><div><strong>{pending.length}</strong><span>Nieuwe aanvragen</span></div><div><strong>{conversations?.length || 0}</strong><span>Gesprekken</span></div><div><strong>{business.verified ? 'Actief' : 'Review'}</strong><span>Profielstatus</span></div></div><section className="dashboard-grid"><div className="dashboard-main"><div className="dashboard-section"><div className="dashboard-section-head"><h2>Nieuwe aanvragen</h2><span>{pending.length}</span></div>{pending.length ? pending.map((match: any) => { const request = match.service_requests; return <article className="provider-request-row" key={match.request_id}><div><span>{request?.category}</span><h3>{request?.description}</h3><p>{request?.postcode} · {request?.preferred_timing}</p></div><ProviderAcceptButton requestId={match.request_id} /></article>; }) : <div className="dashboard-empty">Nieuwe aanvragen verschijnen hier zodra je bedrijf is gematcht.</div>}</div><div className="dashboard-section"><div className="dashboard-section-head"><h2>Gesprekken</h2><span>{conversations?.length || 0}</span></div>{conversations?.length ? conversations.map((conversation: any) => <a className="conversation-row" href={`/messages/${conversation.id}`} key={conversation.id}><MessageCircle /><div><strong>{conversation.service_requests?.category || 'Aanvraag'}</strong><small>{conversation.service_requests?.description || 'Klantgesprek'}</small></div><span>{conversation.status}</span><ArrowRight /></a>) : <div className="dashboard-empty">Nog geen gesprekken.</div>}</div></div><aside className="dashboard-side"><div className="dashboard-section"><div className="dashboard-section-head"><h2>Meldingen</h2></div>{notifications?.map(n => <div className="notification-row" key={n.id}><strong>{n.title}</strong><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString('nl-NL')}</small></div>)}</div></aside></section></div></main>;
}
