import { redirect } from 'next/navigation';
import { ArrowRight, BarChart3, BriefcaseBusiness, Check, CreditCard, MessageCircle, Sparkles } from 'lucide-react';
import { createClient } from '../../lib/supabase/server';
import { ProviderAcceptButton } from '../../components/provider-request-actions';
import { LeadStatusButton } from '../../components/lead-status-button';
import { BillingPortalButton } from '../../components/billing-portal-button';

export default async function ProviderPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/login?next=/provider');
  const { data: business } = await supabase.from('businesses').select('id,name,category,postcode,verified,active').eq('owner_id', user.id).limit(1).maybeSingle();
  if (!business) redirect('/signup/account?role=provider');

  const [{ data: subscription }, { data: plan }, { data: matches }, { data: leads }, { data: conversations }, { data: notifications }, { count: views }, { count: contacts }] = await Promise.all([
    supabase.from('business_subscriptions').select('plan_key,status,current_period_end,stripe_customer_id').eq('business_id', business.id).maybeSingle(),
    supabase.from('business_subscriptions').select('business_plans(name,monthly_price_cents,included_leads,featured)').eq('business_id', business.id).maybeSingle(),
    supabase.from('request_providers').select('request_id,status,invited_at,service_requests(id,category,description,postcode,preferred_timing,status,created_at)').eq('business_id', business.id).order('invited_at', { ascending: false }).limit(30),
    supabase.from('leads').select('id,status,qualified,price_cents,created_at,service_requests(category,description,postcode,preferred_timing)').eq('business_id', business.id).order('created_at', { ascending: false }).limit(20),
    supabase.from('conversations').select('id,status,updated_at,service_requests(category,description)').eq('business_id', business.id).order('updated_at', { ascending: false }).limit(20),
    supabase.from('notifications').select('id,title,body,read_at,created_at').eq('user_id', user.id).order('created_at', { ascending: false }).limit(8),
    supabase.from('analytics_events').select('*', { count: 'exact', head: true }).eq('business_id', business.id).eq('event_name', 'business_view').gte('created_at', new Date(Date.now() - 30 * 86400000).toISOString()),
    supabase.from('analytics_events').select('*', { count: 'exact', head: true }).eq('business_id', business.id).in('event_name', ['business_contact','phone_click','whatsapp_click','website_click']).gte('created_at', new Date(Date.now() - 30 * 86400000).toISOString()),
  ]);

  const pending = (matches || []).filter((item: any) => item.status === 'invited');
  const activePlan = (plan as any)?.business_plans || { name: 'Gratis', monthly_price_cents: 0, included_leads: 3, featured: false };
  const leadCount = leads?.length || 0;

  return <main className="platform-shell"><header className="platform-header"><a className="uo-brand" href="/"><span className="uo-brand-mark">u</span><span>ithoorn<span>.online</span></span></a><nav><a href="/businesses">Diensten</a><a href="/provider/profile">Profiel</a><a className="business-nav-highlight" href="/voor-bedrijven">Groei</a><form action="/api/auth/signout" method="post"><button>Uitloggen</button></form></nav></header><div className="platform-dashboard">
    <div className="provider-profile-strip"><div className="provider-avatar"><BriefcaseBusiness /></div><div><span className="uo-kicker">Bedrijfsdashboard</span><h1>{business.name}</h1><p>{business.category} · {business.postcode || 'Uithoorn'}</p></div><span className={`verification-pill ${business.verified ? 'verified' : ''}`}>{business.verified ? 'Geverifieerd' : 'In beoordeling'}</span></div>
    <div className="monetization-metrics"><div><span>Profielweergaven</span><strong>{views || 0}</strong><small>laatste 30 dagen</small></div><div><span>Contactacties</span><strong>{contacts || 0}</strong><small>telefoon, WhatsApp, website</small></div><div><span>Leads</span><strong>{leadCount}</strong><small>aanvragen ontvangen</small></div><div><span>Plan</span><strong>{activePlan.name}</strong><small>{activePlan.included_leads} leads inbegrepen</small></div></div>
    <section className="business-growth-card"><div><span className="uo-kicker">GROEI MET UITHOORN.ONLINE</span><h2>Maak van lokale zoekopdrachten echte klanten.</h2><p>Je profiel is gratis. Met Pro of Pro+ krijg je meer leadcapaciteit, analytics en promotie.</p></div><a href="/voor-bedrijven">Bekijk plannen <ArrowRight /></a></section>
    <section className="dashboard-grid"><div className="dashboard-main">
      <div className="dashboard-section"><div className="dashboard-section-head"><h2>Nieuwe aanvragen</h2><span>{pending.length}</span></div>{pending.length ? pending.map((match: any) => { const request = match.service_requests; return <article className="provider-request-row" key={match.request_id}><div><span>{request?.category}</span><h3>{request?.description}</h3><p>{request?.postcode} · {request?.preferred_timing}</p></div><ProviderAcceptButton requestId={match.request_id} /></article>; }) : <div className="dashboard-empty">Nieuwe aanvragen verschijnen hier zodra je bedrijf is gematcht.</div>}</div>
      <div className="dashboard-section"><div className="dashboard-section-head"><h2>Leads</h2><span>{leadCount}</span></div>{leads?.length ? leads.map((lead: any) => <article className="lead-row" key={lead.id}><div className="lead-row-copy"><span>{lead.service_requests?.category || 'Aanvraag'}</span><h3>{lead.service_requests?.description || 'Lokale klantvraag'}</h3><p>{lead.service_requests?.postcode || 'Uithoorn'} · {new Date(lead.created_at).toLocaleDateString('nl-NL')}</p></div><div className="lead-row-actions"><span className={`lead-pill lead-${lead.status}`}>{lead.status}</span>{lead.status === 'new' ? <LeadStatusButton leadId={lead.id} status={lead.status} nextStatus="viewed" label="Bekijken" /> : null}{lead.status === 'viewed' ? <LeadStatusButton leadId={lead.id} status={lead.status} nextStatus="accepted" label="Accepteren" /> : null}{lead.status === 'accepted' ? <LeadStatusButton leadId={lead.id} status={lead.status} nextStatus="contacted" label="Contact opgenomen" /> : null}{lead.status === 'contacted' ? <LeadStatusButton leadId={lead.id} status={lead.status} nextStatus="converted" label="Gewonnen" /> : null}</div></article>) : <div className="dashboard-empty">Nog geen leads. Zorg dat je profiel, diensten en werkgebied volledig zijn ingevuld.</div>}</div>
      <div className="dashboard-section"><div className="dashboard-section-head"><h2>Gesprekken</h2><span>{conversations?.length || 0}</span></div>{conversations?.length ? conversations.map((conversation: any) => <a className="conversation-row" href={`/messages/${conversation.id}`} key={conversation.id}><MessageCircle /><div><strong>{conversation.service_requests?.category || 'Aanvraag'}</strong><small>{conversation.service_requests?.description || 'Klantgesprek'}</small></div><span>{conversation.status}</span><ArrowRight /></a>) : <div className="dashboard-empty">Nog geen gesprekken.</div>}</div>
    </div>
    <aside className="dashboard-side"><div className="dashboard-section"><div className="dashboard-section-head"><h2>Je abonnement</h2><CreditCard /></div><div className="plan-summary"><strong>{activePlan.name}</strong><span>{activePlan.monthly_price_cents ? `€${(activePlan.monthly_price_cents / 100).toFixed(0)} / maand` : '€0 / maand'}</span><small>{activePlan.included_leads} leads inbegrepen · {activePlan.featured ? 'promotie inbegrepen' : 'basis profiel'}</small></div><a className="dashboard-side-link" href="/voor-bedrijven">Upgrade naar Pro+ <ArrowRight /></a>{subscription?.stripe_customer_id ? <BillingPortalButton /> : null}</div>
      <div className="dashboard-section"><div className="dashboard-section-head"><h2>Wat je krijgt</h2><Sparkles /></div><ul className="benefit-list"><li><Check /> Lokale klantaanvragen</li><li><Check /> Lead- en contactinzichten</li><li><Check /> Verificatie en vertrouwen</li><li><Check /> Promotie voor betaalde plannen</li></ul></div>
      <div className="dashboard-section"><div className="dashboard-section-head"><h2>Meldingen</h2><BarChart3 /></div>{notifications?.length ? notifications.map(n => <div className="notification-row" key={n.id}><strong>{n.title}</strong><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString('nl-NL')}</small></div>) : <div className="dashboard-empty">Geen nieuwe meldingen.</div>}</div>
    </aside></section></div></main>;
}
