/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoorwaardenRouteImport } from './routes/voorwaarden'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MapRouteImport } from './routes/map'
import { Route as LogRouteImport } from './routes/log'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as CheckRouteImport } from './routes/check'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimIndexRouteImport } from './routes/claim.index'
import { Route as ClaimSuccessRouteImport } from './routes/claim.success'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServicesProviderRouteImport } from './routes/services.provider'
import { Route as FlightNoiseRouteImport } from './routes/flight-noise'
import { Route as ApiPublicHooksRunEvalsRouteImport } from './routes/api/public/hooks/run-evals'
import { Route as ApiPublicHooksIngestKnowledgeRouteImport } from './routes/api/public/hooks/ingest-knowledge'

const VoorwaardenRoute = VoorwaardenRouteImport.update({ id: '/voorwaarden', path: '/voorwaarden', getParentRoute: () => rootRouteImport } as any)
const PrivacyRoute = PrivacyRouteImport.update({ id: '/privacy', path: '/privacy', getParentRoute: () => rootRouteImport } as any)
const MapRoute = MapRouteImport.update({ id: '/map', path: '/map', getParentRoute: () => rootRouteImport } as any)
const LogRoute = LogRouteImport.update({ id: '/log', path: '/log', getParentRoute: () => rootRouteImport } as any)
const ClaimRoute = ClaimRouteImport.update({ id: '/claim', path: '/claim', getParentRoute: () => rootRouteImport } as any)
const CheckRoute = CheckRouteImport.update({ id: '/check', path: '/check', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const ClaimIndexRoute = ClaimIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => ClaimRoute } as any)
const ClaimSuccessRoute = ClaimSuccessRouteImport.update({ id: '/success', path: '/success', getParentRoute: () => ClaimRoute } as any)
const ServicesRoute = ServicesRouteImport.update({ id: '/services', path: '/services', getParentRoute: () => rootRouteImport } as any)
const ServicesProviderRoute = ServicesProviderRouteImport.update({ id: '/services/provider', path: '/services/provider', getParentRoute: () => rootRouteImport } as any)
const FlightNoiseRoute = FlightNoiseRouteImport.update({ id: '/flight-noise', path: '/flight-noise', getParentRoute: () => rootRouteImport } as any)
const ApiPublicHooksRunEvalsRoute = ApiPublicHooksRunEvalsRouteImport.update({ id: '/api/public/hooks/run-evals', path: '/api/public/hooks/run-evals', getParentRoute: () => rootRouteImport } as any)
const ApiPublicHooksIngestKnowledgeRoute = ApiPublicHooksIngestKnowledgeRouteImport.update({ id: '/api/public/hooks/ingest-knowledge', path: '/api/public/hooks/ingest-knowledge', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/claim': typeof ClaimRouteWithChildren
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/services': typeof ServicesRoute
  '/services/provider': typeof ServicesProviderRoute
  '/flight-noise': typeof FlightNoiseRoute
  '/claim/success': typeof ClaimSuccessRoute
  '/claim/': typeof ClaimIndexRoute
  '/api/public/hooks/ingest-knowledge': typeof ApiPublicHooksIngestKnowledgeRoute
  '/api/public/hooks/run-evals': typeof ApiPublicHooksRunEvalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/services': typeof ServicesRoute
  '/services/provider': typeof ServicesProviderRoute
  '/flight-noise': typeof FlightNoiseRoute
  '/claim/success': typeof ClaimSuccessRoute
  '/claim': typeof ClaimIndexRoute
  '/api/public/hooks/ingest-knowledge': typeof ApiPublicHooksIngestKnowledgeRoute
  '/api/public/hooks/run-evals': typeof ApiPublicHooksRunEvalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/claim': typeof ClaimRouteWithChildren
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/services': typeof ServicesRoute
  '/services/provider': typeof ServicesProviderRoute
  '/flight-noise': typeof FlightNoiseRoute
  '/claim/success': typeof ClaimSuccessRoute
  '/claim/': typeof ClaimIndexRoute
  '/api/public/hooks/ingest-knowledge': typeof ApiPublicHooksIngestKnowledgeRoute
  '/api/public/hooks/run-evals': typeof ApiPublicHooksRunEvalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/check' | '/claim' | '/log' | '/map' | '/privacy' | '/voorwaarden' | '/services' | '/services/provider' | '/flight-noise' | '/claim/success' | '/claim/' | '/api/public/hooks/ingest-knowledge' | '/api/public/hooks/run-evals'
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}

declare module '@tanstack/react-router' { interface FileRoutesByPath {
  '/voorwaarden': { id: '/voorwaarden'; path: '/voorwaarden'; fullPath: '/voorwaarden'; preLoaderRoute: typeof VoorwaardenRouteImport; parentRoute: typeof rootRouteImport }
  '/privacy': { id: '/privacy'; path: '/privacy'; fullPath: '/privacy'; preLoaderRoute: typeof PrivacyRouteImport; parentRoute: typeof rootRouteImport }
  '/map': { id: '/map'; path: '/map'; fullPath: '/map'; preLoaderRoute: typeof MapRouteImport; parentRoute: typeof rootRouteImport }
  '/log': { id: '/log'; path: '/log'; fullPath: '/log'; preLoaderRoute: typeof LogRouteImport; parentRoute: typeof rootRouteImport }
  '/claim': { id: '/claim'; path: '/claim'; fullPath: '/claim'; preLoaderRoute: typeof ClaimRouteImport; parentRoute: typeof rootRouteImport }
  '/check': { id: '/check'; path: '/check'; fullPath: '/check'; preLoaderRoute: typeof CheckRouteImport; parentRoute: typeof rootRouteImport }
  '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
  '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  '/services': { id: '/services'; path: '/services'; fullPath: '/services'; preLoaderRoute: typeof ServicesRouteImport; parentRoute: typeof rootRouteImport }
  '/services/provider': { id: '/services/provider'; path: '/services/provider'; fullPath: '/services/provider'; preLoaderRoute: typeof ServicesProviderRouteImport; parentRoute: typeof rootRouteImport }
  '/flight-noise': { id: '/flight-noise'; path: '/flight-noise'; fullPath: '/flight-noise'; preLoaderRoute: typeof FlightNoiseRouteImport; parentRoute: typeof rootRouteImport }
  '/claim/': { id: '/claim/'; path: '/'; fullPath: '/claim/'; preLoaderRoute: typeof ClaimIndexRouteImport; parentRoute: typeof ClaimRoute }
  '/claim/success': { id: '/claim/success'; path: '/success'; fullPath: '/claim/success'; preLoaderRoute: typeof ClaimSuccessRouteImport; parentRoute: typeof ClaimRoute }
  '/api/public/hooks/run-evals': { id: '/api/public/hooks/run-evals'; path: '/api/public/hooks/run-evals'; fullPath: '/api/public/hooks/run-evals'; preLoaderRoute: typeof ApiPublicHooksRunEvalsRouteImport; parentRoute: typeof rootRouteImport }
  '/api/public/hooks/ingest-knowledge': { id: '/api/public/hooks/ingest-knowledge'; path: '/api/public/hooks/ingest-knowledge'; fullPath: '/api/public/hooks/ingest-knowledge'; preLoaderRoute: typeof ApiPublicHooksIngestKnowledgeRouteImport; parentRoute: typeof rootRouteImport }
} }
interface ClaimRouteChildren { ClaimSuccessRoute: typeof ClaimSuccessRoute; ClaimIndexRoute: typeof ClaimIndexRoute }
const ClaimRouteChildren: ClaimRouteChildren = { ClaimSuccessRoute, ClaimIndexRoute }
const ClaimRouteWithChildren = ClaimRoute._addFileChildren(ClaimRouteChildren)
const rootRouteChildren = { IndexRoute, AuthRoute, CheckRoute, ClaimRoute: ClaimRouteWithChildren, LogRoute, MapRoute, PrivacyRoute, VoorwaardenRoute, ServicesRoute, ServicesProviderRoute, FlightNoiseRoute, ApiPublicHooksIngestKnowledgeRoute, ApiPublicHooksRunEvalsRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>> } }
