/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as LogRouteImport } from './routes/log'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as CheckRouteImport } from './routes/check'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksRunEvalsRouteImport } from './routes/api/public/hooks/run-evals'
import { Route as ApiPublicHooksIngestKnowledgeRouteImport } from './routes/api/public/hooks/ingest-knowledge'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunEvalsRoute = ApiPublicHooksRunEvalsRouteImport.update({
  id: '/api/public/hooks/run-evals',
  path: '/api/public/hooks/run-evals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestKnowledgeRoute =
  ApiPublicHooksIngestKnowledgeRouteImport.update({
    id: '/api/public/hooks/ingest-knowledge',
    path: '/api/public/hooks/ingest-knowledge',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/claim': typeof ClaimRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/api/public/hooks/ingest-knowledge': typeof ApiPublicHooksIngestKnowledgeRoute
  '/api/public/hooks/run-evals': typeof ApiPublicHooksRunEvalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/claim': typeof ClaimRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/api/public/hooks/ingest-knowledge': typeof ApiPublicHooksIngestKnowledgeRoute
  '/api/public/hooks/run-evals': typeof ApiPublicHooksRunEvalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/claim': typeof ClaimRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/api/public/hooks/ingest-knowledge': typeof ApiPublicHooksIngestKnowledgeRoute
  '/api/public/hooks/run-evals': typeof ApiPublicHooksRunEvalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/check'
    | '/claim'
    | '/log'
    | '/map'
    | '/api/public/hooks/ingest-knowledge'
    | '/api/public/hooks/run-evals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/check'
    | '/claim'
    | '/log'
    | '/map'
    | '/api/public/hooks/ingest-knowledge'
    | '/api/public/hooks/run-evals'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/check'
    | '/claim'
    | '/log'
    | '/map'
    | '/api/public/hooks/ingest-knowledge'
    | '/api/public/hooks/run-evals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckRoute: typeof CheckRoute
  ClaimRoute: typeof ClaimRoute
  LogRoute: typeof LogRoute
  MapRoute: typeof MapRoute
  ApiPublicHooksIngestKnowledgeRoute: typeof ApiPublicHooksIngestKnowledgeRoute
  ApiPublicHooksRunEvalsRoute: typeof ApiPublicHooksRunEvalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-evals': {
      id: '/api/public/hooks/run-evals'
      path: '/api/public/hooks/run-evals'
      fullPath: '/api/public/hooks/run-evals'
      preLoaderRoute: typeof ApiPublicHooksRunEvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-knowledge': {
      id: '/api/public/hooks/ingest-knowledge'
      path: '/api/public/hooks/ingest-knowledge'
      fullPath: '/api/public/hooks/ingest-knowledge'
      preLoaderRoute: typeof ApiPublicHooksIngestKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckRoute: CheckRoute,
  ClaimRoute: ClaimRoute,
  LogRoute: LogRoute,
  MapRoute: MapRoute,
  ApiPublicHooksIngestKnowledgeRoute: ApiPublicHooksIngestKnowledgeRoute,
  ApiPublicHooksRunEvalsRoute: ApiPublicHooksRunEvalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
